theme: jekyll-theme-cayman
title: Dofus Meter
show_downloads: "true"

github:
    zip_url: https://github.com/DofusMeter/archive/raw/master/DofusMeter.zip

defaults:
  - scope:
      path: "fr"
    values:
      lang: "fr"
  - scope:
      path: "en"
    values:
      lang: "en"
